"""create tables 2

Revision ID: 47feb3a72520
Revises: 5123280468ed
Create Date: 2024-06-20 07:41:04.771582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47feb3a72520'
down_revision: Union[str, None] = '5123280468ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'achievements', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='unique')
    # ### end Alembic commands ###
